AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hello World with SAM

Globals:
  Function:
    MemorySize: 128
    Runtime: node.js
    Timeout: 5

Resources:
  eventLoger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logger.handler
      Timeout: 3

  addNumbers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.handler

  TestAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
