AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hello World with SAM

Globals:
  Function:
    MemorySize: 128
    Runtime: node.js
    Timeout: 5

Resources:
  eventLoger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logger.handler
      Timeout: 3
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
        FileUpload:
          Type: S3
          Properties:
            Bucket: MyBucket
            Events: s3:objectCreated:*

  MyBucket:
    Type: AWS::S3::Bucket

  addNumbers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.handler
